In [ ]:
#reading daata from csv file

In [1]:
import csv

In [2]:
with open("abc.csv") as file:
    contents = csv.reader(file)
    for content in contents:
        print(content)

['Year', 'Event', 'Winner']
['1995.Best-Keot Lawn', 'None']
['1999', 'Gobstones', 'Welch National']
['2006', 'World Cup', 'Burkina Faso']

In [ ]:
#creating and writing inn na new csv file

In [6]:
with open("xyz.csv","w",newline="") as file:
    fileWriter = csv.writer(file)
    fileWriter.writerow(["2019","CWC2019","ENG"])

In [ ]:
#appending in a csv file

In [9]:
with open("xyz.csv","a",newline="") as file:
    fileWriter = csv.writer(file)
    fileWriter.writerow(["2020","CWC2020","PAK"])
    #you can add as many rows as you want

In [1]:
import numpy as np 
import pandas as pd

In [27]:
sample_df=pd.read_csv("Sample2.csv")

In [38]:
parsed=pd.read_csv("Sample2.csv",index_col=['key1','key2'])

In [35]:
#dfatt=pd.DataFrame(sample_df)
#print(sample_df.head)

In [36]:
parsed.ad

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [46]:
att=pd.read_csv("Attendance_Sheet.csv",index_col=0)

In [70]:
sanitals={'5': ['P','p']}
pd.read_csv("Attendance_Sheet.csv",na_values=sanitals,index_col=0)

,1,2,3,4,5,6,7,8,9,10,...,19,20,21,22,23,24,25,26,27,28
Date/Roll No,,,,,,,,,,,,,,,,,,,,,
1,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,a,p,p,p,p,p,a
2,p,p,p,p,NaN,p,a,p,p,p,...,p,p,p,p,p,p,p,p,p,p
3,p,p,p,p,NaN,a,a,a,p,a,...,a,a,a,a,a,a,p,a,a,a
4,p,a,p,p,a,p,p,a,p,p,...,p,p,p,p,p,p,p,p,p,p
5,p,p,p,p,NaN,p,p,a,p,p,...,p,p,a,p,a,a,p,p,p,p
6,p,a,p,p,a,p,p,a,p,p,...,p,p,p,p,p,p,a,p,p,p
7,p,a,p,p,NaN,p,p,p,p,p,...,p,p,p,p,p,p,p,p,p,a
8,p,p,p,a,a,p,a,a,p,p,...,p,p,p,p,p,p,p,p,p,p
9,p,p,p,p,a,p,a,p,p,p,...,p,p,p,p,a,p,p,p,a,p
10,p,a,p,a,NaN,p,a,a,a,p,...,a,a,p,a,a,p,p,a,p,p
11,p,a,p,p,NaN,p,a,p,p,p,...,p,p,a,p,a,p,p,p,p,p
12,p,a,a,a,NaN,p,p,a,a,p,...,p,p,a,p,p,p,p,p,p,p
13,p,p,p,p,NaN,a,a,p,a,a,...,a,p,a,a,p,p,a,p,a,a
14,p,p,p,p,a,a,p,p,p,p,...,p,p,p,p,p,p,a,p,p,p
15,p,p,p,p,NaN,p,p,p,p,p,...,p,p,a,p,a,p,p,p,p,p
16,p,a,p,p,NaN,p,p,a,p,p,...,a,p,p,a,p,a,p,p,a,a
17,p,a,p,p,NaN,a,p,p,p,p,...,p,p,a,p,p,p,p,p,p,p
18,p,a,a,p,NaN,a,p,a,p,p,...,p,p,p,p,p,p,p,p,p,p
19,p,p,p,p,NaN,a,p,p,p,p,...,p,p,p,p,p,p,p,p,a,p
20,p,p,p,a,NaN,p,p,a,p,p,...,p,p,p,a,p,p,p,p,p,p
21,a,p,p,p,a,p,p,p,p,p,...,p,a,a,p,p,p,a,a,p,p
22,p,p,p,p,a,p,a,p,p,p,...,p,p,p,p,p,p,p,p,p,p
23,p,a,p,p,NaN,p,p,p,p,p,...,p,p,p,p,p,p,p,p,p,p
24,p,p,p,p,a,p,p,p,p,p,...,p,p,p,p,p,p,p,p,p,a
25,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,p,p,a,p,p,p,p
26,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,p,p,p,p,p,p,p
27,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,p,a,p,p,p,p,p
28,a,a,a,a,NaN,a,a,a,p,p,...,a,a,a,p,a,p,a,a,a,a
29,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,p,a,p,p,p,p,p
30,p,a,a,p,NaN,p,p,p,p,p,...,p,p,a,p,p,p,p,p,p,p
31,p,p,p,p,NaN,a,a,a,a,a,...,p,p,a,p,p,p,p,a,p,a
32,p,p,p,p,NaN,p,p,p,p,p,...,p,p,a,p,a,p,a,p,p,p
33,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,p,p,p,p,p,a,p
34,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,p,p,p,p,p,p,p
35,p,p,p,p,NaN,p,p,p,p,p,...,p,p,p,p,p,p,p,p,p,p
36,a,a,a,p,NaN,a,a,a,p,p,...,a,a,a,a,a,a,p,a,p,p

In [67]:
senitals= {'message' : ['foo','Nan']}
result=pd.read_csv('Sample3.csv',na_values=senitals)

In [68]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [78]:
#pd.read_csv('train.csv',nrows=200)

In [91]:
chunks=pd.read_csv('train.csv',chunksize=200)

chunklist =[]

for chunk in chunks:
    print(type(chunk) ,len(chunk))
    #print(chunk.head())
    chunklist.append(chunk)

chunklist[0].head()

<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200
<class 'pandas.core.frame.DataFrame'> 200

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [83]:
print(chunks)

<pandas.io.parsers.TextFileReader object at 0x0000025B0C170668>

In [96]:
dates = pd.date_range('1/1/2000',periods=7)
print(dates)

ts=pd.Series(np.arange(7),index=dates)

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [114]:
ts.to_csv('tseries.csv')

In [115]:
import csv
f=open('Sample2.csv')

In [116]:
reader = csv.reader(f)
for line in reader:
    print(line)

['key1', 'key2', 'value1', 'value2']
['one', 'a', '1', '2']
['one', 'b', '3', '4']
['one', 'c', '5', '6']
['one', 'd', '7', '8']
['two', 'a', '9', '10']
['two', 'b', '11', '12']
['two', 'c', '13', '14']
['two', 'd', '15', '16']

In [117]:
import pandas as pd
tables= pd.read_html('fdic_failed_bank_list.html')
#print(type(tables))

ImportError: lxml not found, please install it

In [2]:
import BeautifulSoup
soup = BeautifulSoup(txt, 'lxml')

ModuleNotFoundError: No module named 'BeautifulSoup'